# Generated by Django 5.2 on 2025-05-05 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_users_password_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='working_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
